[tool.poetry]
name = "htbam-analysis"
version = "0.2.0"
description = ""
authors = ["duncan-muir <muir.duncan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.10"
numpy = "1.23.1"
opencv-python = "4.6.0.66"
opencv-contrib-python = "4.6.0.66"
ipywidgets = "7.7.1"
tqdm = "4.64.0"
pytest = "^7.4.3"
basicpy = "^1.1.0"
pillow = "9.2.0"
matplotlib = "3.5.2"
scikit-image = "0.19.3"
pandas = "1.4.3"
scipy = "1.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
